config/routes.rb
BcProto3::Application.routes.draw do

  resources :documentos do
    member do 
      get 'indexar'
      get 'datos_documento' #Llena con datos de un documento la ventana modal
    end#do
    collection do 
      get 'dashboard'
    end#do
  end#do

  match 'subir_archivo/:id'          => 'documentos#subir_archivo'
  match 'guardar_archivo'            => 'documentos#guardar_archivo'
  match 'guardar_archivo_conest'     => 'documentos#guardar_archivo_conest'
  match 'subir_teg_hacia_busconest'  => 'documentos#crear_teg_desde_conest'

  resources :personas do
    member do 
      get 'datos_persona' #Llena con datos de una persona en la ventana modal
    end#do
    collection do 
      get 'autocompletar_personas'
    end#do
  end#do

  root :to => "busquedas#busqueda_simple"

  match 'admin' => 'documentos#index'

  devise_for :usuarios, :path_names => { :sign_in => 'iniciar_sesion', :sign_out => 'cerrar_sesion' }

  resources :areas

  resources :estudiantes do
    member do 
      get 'datos_estudiante' #Llena con datos de un estudiante en la ventana modal
    end#do
  end#do

  resources :premios

  resources :mencions

  resources :reconocimientos

  resources :idiomas

  resources :tipo_documentos

  match 'busqueda_simple'     => 'busquedas#busqueda_simple'

  match 'directorio'                   => 'busquedas#directorio'

  match 'directorio/escuelas/:escuela' => 'busquedas#directorio_escuela', :escuela => /biologia|computacion|fisica|geoquimica|matematica|quimica/
  match 'directorio/tipos/:tipo'       => 'busquedas#directorio_tipo'

  match 'directorio/fechas/:fecha'     => 'busquedas#directorio_fecha', :fecha => /(1|2)\d{3}/

  match 'busqueda_avanzada'            => 'busquedas#busqueda_avanzada'

  match 'documentos/descargar/:id'     => 'documentos#descargar'

end

app/models/idioma.rb
class Idioma < ActiveRecord::Base
  include Utilidades

  attr_accessible :codigo, :descripcion

  has_many :documentos, :dependent => :restrict

  validates :descripcion, :length => { :in => 1..25 }, :uniqueness => true

  validates :codigo, :format => { :with => /\A[a-z]{2}\z/, :codigo => "no es un valor ISO 639-1 valido" }, :uniqueness => true

  before_validation do |idioma|
    eliminar_acentos!(idioma.descripcion).upcase!
  end
end

app/controllers/idiomas_controller.rb
class IdiomasController < AdminController
  include Utilidades

  # GET /idiomas
  # GET /idiomas.json
  def index
    @idiomas = Idioma.order("descripcion").paginate(:page => params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @idiomas }
    end
  end

  # GET /idiomas/1
  # GET /idiomas/1.json
  def show
    @idioma = Idioma.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @idioma }
    end
  end

  # GET /idiomas/new
  # GET /idiomas/new.json
  def new
    @idioma = Idioma.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @idioma }
    end
  end

  # GET /idiomas/1/edit
  def edit
    @idioma = Idioma.find(params[:id])
  end

  # POST /idiomas
  # POST /idiomas.json
  def create

    @idioma = Idioma.new(params[:idioma])

    respond_to do |format|
      if @idioma.save
        format.html { redirect_to @idioma, notice: 'Idioma creado' }
        format.json { render json: @idioma, status: :created, location: @idioma }
      else
        format.html { render action: "new" }
        format.json { render json: @idioma.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /idiomas/1
  # PUT /idiomas/1.json
  def update
    @idioma = Idioma.find(params[:id])

    respond_to do |format|
      if @idioma.update_attributes(params[:idioma])
        format.html { redirect_to @idioma, notice: 'Idioma actualizado' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @idioma.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /idiomas/1
  # DELETE /idiomas/1.json
  def destroy
    @idioma = Idioma.find(params[:id])

    eliminar_recurso?(@idioma) ? notice_msj = "#{@idioma.descripcion} eliminado" : alert_msj = "No se puede eliminar #{@idioma.descripcion} porque tiene al menos un documento asociado"

    respond_to do |format|
      format.html { redirect_to idiomas_url, alert: alert_msj, notice: notice_msj }
      format.json { head :no_content }
    end#do
  end#def
end#class

app/helpers/idiomas_helper.rb
module IdiomasHelper
end

app/views/idiomas/_form.html.erb
<div class="upload_form_cont">


<%= form_for(@idioma) do |f| %>

  <%= render :partial => 'shared/errores', :locals => { :modelo => @idioma } %>'

  <div class="control-group">
    <%= f.label :descripcion, :style => "", :class => "control-label", :style => "width:20%" %>
    <div class="controls">
      <%= f.text_field :descripcion, :style => "width:70%", :maxlength => 25  %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label 'codigo * (minuscula)', :class => "control-label", :style => "width:20%" %>
    <div class="controls">
      <%= f.text_field :codigo, :style => "width:70%", :maxlength => 2 %>
      <p>* El codigo del idioma segun la norma <a href="http://es.wikipedia.org/wiki/ISO_639-1" target="_blank">ISO 639-1</a></p>
    </div>
  </div>

  <div class="control-group" style = "text-align:right; width:70%">
    <%= link_to idiomas_path, { :class => 'btn-black', :style => "color:white"} do %>
      <i class="icon-white icon-remove"></i> Cancelar 
    <% end %> 
    <%= f.submit 'Guardar', :class => 'btn btn-info', :style => "color:white; margin-left: 5px"  %>
  </div>

<% end %>



</div>

app/views/idiomas/edit.html.erb
<% titulo 'Editar Idioma' %>

<%= render 'form' %>

<!--
<%= link_to @idioma, { :class => 'btn-black', :style => "color:white"} do %>
  <i class="icon-white icon-search"></i> Ver 
<% end %>
-->

app/views/idiomas/index.html.erb
<% titulo 'Idiomas' %>

<%= link_to  new_idioma_path, { :class => 'btn-black', :style => "color:white;"} do %>
  <i class="icon-white icon-plus"></i> Crear Idioma
<% end %>
<br/><br/>

<table class="table table-striped tabla">
  <thead  class="head-blue">
  <tr>
    <th>Descripcion</th>
    <th>Codigo</th>
    <th style="width:30%">Acciones</th>
  </tr>
  </thead>
  <tbody>
<% @idiomas.each do |idioma| %>
  <tr>
    <td><p class="desc"><%= idioma.descripcion %></p></td>
    <td><%= idioma.codigo %></td>
    <td><!-- <%= link_to idioma, { :class => 'btn btn-info', :style => "color:white"} do %> 
          <i class="icon-white icon-search"></i> Ver 
        <% end %> -->
        <%= link_to edit_idioma_path(idioma), { :class => 'btn btn-info', :style => "color:white"} do %> 
	  <i class="icon-white icon-edit"></i> Editar 
        <% end %>
        <%= link_to idioma, { :class => 'btn btn-danger', :style => "color:white", method: :delete,  
	  data: { confirm: "¿Estas seguro que quieres eliminar #{idioma.descripcion}?"} } do %> 
          <i class="icon-white icon-remove"></i> Eliminar 
        <% end %>
    </td>
  </tr>
<% end %>
</tbody>
</table>

<%= render :partial => 'shared/paginacion', :locals => { :coleccion => @idiomas } %>

<%= render 'shared/modal' %>

app/views/idiomas/new.html.erb
<% titulo 'Nuevo Idioma' %>

<%= render 'form' %>

app/views/idiomas/show.html.erb
<% titulo 'Idioma' %>

<div class="grid-row" >
  <div class="labels">Descripcion:</div> 
  <div class="values"><%=  @idioma.descripcion %></div> 
</div>

<div class="grid-row" >
  <div class="labels">Código:</div> 
  <div class="values"><%=  @idioma.codigo %></div> 
</div>

<br />

<nav>
  <%= link_to idiomas_path, { :class => 'btn-black', :style => "color:white;"} do %>
    <i class="icon-white icon-arrow-left"></i> Volver 
  <% end %>
  <%= link_to '/admin', { :class => 'btn-black', :style => "color:white"} do %>
    <i class="icon-white icon-book"></i> Ir a Admin 
  <% end %>
  <%= link_to edit_idioma_path(@idioma), { :class => 'btn-black', :style => "color:white"} do %>
    <i class="icon-white icon-edit"></i> Editar 
  <% end %>
</nav>