config/routes.rb
BcProto3::Application.routes.draw do

  resources :documentos do
    member do 
      get 'indexar'
      get 'datos_documento' #Llena con datos de un documento la ventana modal
    end#do
    collection do 
      get 'dashboard'
    end#do
  end#do

  match 'subir_archivo/:id'          => 'documentos#subir_archivo'
  match 'guardar_archivo'            => 'documentos#guardar_archivo'
  match 'guardar_archivo_conest'     => 'documentos#guardar_archivo_conest'
  match 'subir_teg_hacia_busconest'  => 'documentos#crear_teg_desde_conest'

  resources :personas do
    member do 
      get 'datos_persona' #Llena con datos de una persona en la ventana modal
    end#do
    collection do 
      get 'autocompletar_personas'
    end#do
  end#do

  root :to => "busquedas#busqueda_simple"

  match 'admin' => 'documentos#index'

  devise_for :usuarios, :path_names => { :sign_in => 'iniciar_sesion', :sign_out => 'cerrar_sesion' }

  resources :areas

  resources :estudiantes do
    member do 
      get 'datos_estudiante' #Llena con datos de un estudiante en la ventana modal
    end#do
  end#do

  resources :premios

  resources :mencions

  resources :reconocimientos

  resources :idiomas

  resources :tipo_documentos

  match 'busqueda_simple'     => 'busquedas#busqueda_simple'

  match 'directorio'                   => 'busquedas#directorio'

  match 'directorio/escuelas/:escuela' => 'busquedas#directorio_escuela', :escuela => /biologia|computacion|fisica|geoquimica|matematica|quimica/
  match 'directorio/tipos/:tipo'       => 'busquedas#directorio_tipo'

  match 'directorio/fechas/:fecha'     => 'busquedas#directorio_fecha', :fecha => /(1|2)\d{3}/

  match 'busqueda_avanzada'            => 'busquedas#busqueda_avanzada'

  match 'documentos/descargar/:id'     => 'documentos#descargar'

end

app/models/mencion.rb
class Mencion < ActiveRecord::Base
  include Utilidades

  # 10 menciones por pagina (will_paginate setting)
  self.per_page = 10

  attr_accessible :descripcion, :escuela_id

  belongs_to :escuela

  has_many :estudiantes, :dependent => :restrict

  validates :descripcion, :length => { :in => 1..100 }, :uniqueness => { scope: :escuela_id }

  validates :escuela_id, :presence => true

  before_validation do |mencion|
    eliminar_acentos!(mencion.descripcion).upcase!
  end
end

app/controllers/mencions_controller.rb
class MencionsController < AdminController
  include Utilidades

  # GET /mencions
  # GET /mencions.json
  def index
    @mencions = Mencion.order("escuela_id").paginate(:page => params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @mencions }
    end
  end

  # GET /mencions/1
  # GET /mencions/1.json
  def show
    @mencion = Mencion.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @mencion }
    end
  end

  # GET /mencions/new
  # GET /mencions/new.json
  def new
    @mencion = Mencion.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @mencion }
    end
  end

  # GET /mencions/1/edit
  def edit
    @mencion = Mencion.find(params[:id])
  end

  # POST /mencions
  # POST /mencions.json
  def create
    @mencion = Mencion.new(params[:mencion])

    respond_to do |format|
      if @mencion.save
        format.html { redirect_to @mencion, notice: 'Mencion creada' }
        format.json { render json: @mencion, status: :created, location: @mencion }
      else
        format.html { render action: "new" }
        format.json { render json: @mencion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /mencions/1
  # PUT /mencions/1.json
  def update
    @mencion = Mencion.find(params[:id])

    respond_to do |format|
      if @mencion.update_attributes(params[:mencion])
        format.html { redirect_to @mencion, notice: 'Mencion actualizada' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @mencion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mencions/1
  # DELETE /mencions/1.json
  def destroy
    @mencion = Mencion.find(params[:id])

    eliminar_recurso?(@mencion) ? notice_msj = "#{@mencion.descripcion} eliminada" : alert_msj = "No se puede eliminar #{@mencion.descripcion} porque hay al menos un estudiante asociado" 

    respond_to do |format|
      format.html { redirect_to mencions_url, alert: alert_msj, notice: notice_msj }
      format.json { head :no_content }
    end
  end
end

app/helpers/mencions_helper.rb
module MencionsHelper
end

app/views/mencions/_form.html.erb
<%= form_for(@mencion) do |f| %>

  <%= render :partial => 'shared/errores', :locals => { :modelo => @mencion } %>'

  <div class="control-group">
    <%= f.label :descripcion, :style => "", :class => "control-label", :style => "width:20%" %>
    <div class="controls">
      <%= f.text_field :descripcion, :style => "width:70%", :rows => "4"  %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :escuela, :style => "", :class => "control-label", :style => "width:20%" %>
    <div class="controls">
      <%= f.select("escuela_id", Escuela.all.collect {|p| [ p.descripcion, p.id ] }) %>
    </div>
  </div>

  <div class="control-group" style = "text-align:right; width:70%">
    <%= link_to mencions_path, { :class => 'btn-black', :style => "color:white"} do %>
      <i class="icon-white icon-remove"></i> Cancelar 
    <% end %> 
    <%= f.submit 'Guardar', :class => 'btn btn-info', :style => "color:white; margin-left: 5px"  %>
  </div>

<% end %>

app/views/mencions/edit.html.erb
<% titulo 'Editar Mencion' %>

<%= render 'form' %>

<!--
<%= link_to @mencion, { :class => 'btn-black', :style => "color:white"} do %>
  <i class="icon-white icon-search"></i> Ver 
<% end %>
-->

app/views/mencions/index.html.erb
<% titulo 'Menciones' %>

<%= link_to  new_mencion_path, { :class => 'btn-black', :style => "color:white;"} do %>
  <i class="icon-white icon-plus"></i> Crear Mencion 
<% end %>
<br/><br/>

<table class="table table-striped tabla">
  <thead  class="head-blue">
  <tr>
    <th>Descripcion</th>
    <th>Escuela</th>
    <th style="width:30%">Acciones</th>
  </tr>
  </thead>
  <tbody>
<% @mencions.each do |mencion| %>
  <tr>
    <td><p class="desc"><%= mencion.descripcion %></p></td>
    <td><%= mencion.escuela.descripcion %></td>
    <td><!-- <%= link_to mencion, { :class => 'btn btn-info', :style => "color:white"} do %> 
          <i class="icon-white icon-search"></i> Ver 
        <% end %> -->
        <%= link_to edit_mencion_path(mencion), { :class => 'btn btn-info', :style => "color:white"} do %> 
	  <i class="icon-white icon-edit"></i> Editar 
        <% end %>
        <%= link_to mencion, { :class => 'btn btn-danger', :style => "color:white", method: :delete,  
	  data: { confirm: "¿Estas seguro que quieres eliminar #{mencion.descripcion}?"} } do %> 
          <i class="icon-white icon-remove"></i> Eliminar 
        <% end %>
    </td>

  </tr>
<% end %>
  </tbody>
</table>

<%= render :partial => 'shared/paginacion', :locals => { :coleccion => @mencions } %>

<%= render 'shared/modal' %>

app/views/mencions/new.html.erb
<% titulo 'Nueva Mencion' %>

<%= render 'form' %>

app/views/mencions/show.html.erb
<% titulo 'Mencion' %>

<div class="grid-row" >
  <div class="labels">Descripcion:</div> 
  <div class="values"><%= @mencion.descripcion %></div> 
</div>  
<div class="grid-row" >
   <div class="labels">Escuela:</div> 
   <div class="values"><%= @mencion.escuela.descripcion %></div> 
</div>  

<br />

<nav>
  <%= link_to mencions_path, { :class => 'btn-black', :style => "color:white;"} do %>
    <i class="icon-white icon-arrow-left"></i> Volver 
  <% end %>
  <%= link_to '/admin', { :class => 'btn-black', :style => "color:white"} do %>
    <i class="icon-white icon-book"></i> Ir a Admin 
  <% end %>
  <%= link_to edit_mencion_path(@mencion), { :class => 'btn-black', :style => "color:white"} do %>
    <i class="icon-white icon-edit"></i> Editar 
  <% end %>
</nav>