config/routes.rb
BcProto3::Application.routes.draw do

  resources :documentos do
    member do 
      get 'indexar'
      get 'datos_documento' #Llena con datos de un documento la ventana modal
    end#do
    collection do 
      get 'dashboard'
    end#do
  end#do

  match 'subir_archivo/:id'          => 'documentos#subir_archivo'
  match 'guardar_archivo'            => 'documentos#guardar_archivo'
  match 'guardar_archivo_conest'     => 'documentos#guardar_archivo_conest'
  match 'subir_teg_hacia_busconest'  => 'documentos#crear_teg_desde_conest'

  resources :personas do
    member do 
      get 'datos_persona' #Llena con datos de una persona en la ventana modal
    end#do
    collection do 
      get 'autocompletar_personas'
    end#do
  end#do

  root :to => "busquedas#busqueda_simple"

  match 'admin' => 'documentos#index'

  devise_for :usuarios, :path_names => { :sign_in => 'iniciar_sesion', :sign_out => 'cerrar_sesion' }

  resources :areas

  resources :estudiantes do
    member do 
      get 'datos_estudiante' #Llena con datos de un estudiante en la ventana modal
    end#do
  end#do

  resources :premios

  resources :mencions

  resources :reconocimientos

  resources :idiomas

  resources :tipo_documentos

  match 'busqueda_simple'     => 'busquedas#busqueda_simple'

  match 'directorio'                   => 'busquedas#directorio'

  match 'directorio/escuelas/:escuela' => 'busquedas#directorio_escuela', :escuela => /biologia|computacion|fisica|geoquimica|matematica|quimica/
  match 'directorio/tipos/:tipo'       => 'busquedas#directorio_tipo'

  match 'directorio/fechas/:fecha'     => 'busquedas#directorio_fecha', :fecha => /(1|2)\d{3}/

  match 'busqueda_avanzada'            => 'busquedas#busqueda_avanzada'

  match 'documentos/descargar/:id'     => 'documentos#descargar'

end

app/models/reconocimiento.rb
class Reconocimiento < ActiveRecord::Base
  include Utilidades

  attr_accessible :descripcion

  has_and_belongs_to_many :documentos

  validates :descripcion, :length => { :in => 1..100 }, :uniqueness => true

  before_validation do |reconocimiento|
    eliminar_acentos!(reconocimiento.descripcion).upcase!
  end
end

app/controllers/reconocimientos_controller.rb
class ReconocimientosController < AdminController

  # GET /reconocimientos
  # GET /reconocimientos.json
  def index
    @reconocimientos = Reconocimiento.order("descripcion").paginate(:page => params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @reconocimientos }
    end
  end

  # GET /reconocimientos/1
  # GET /reconocimientos/1.json
  def show
    @reconocimiento = Reconocimiento.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @reconocimiento }
    end
  end

  # GET /reconocimientos/new
  # GET /reconocimientos/new.json
  def new
    @reconocimiento = Reconocimiento.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @reconocimiento }
    end
  end

  # GET /reconocimientos/1/edit
  def edit
    @reconocimiento = Reconocimiento.find(params[:id])
  end

  # POST /reconocimientos
  # POST /reconocimientos.json
  def create
    @reconocimiento = Reconocimiento.new(params[:reconocimiento])

    respond_to do |format|
      if @reconocimiento.save
        format.html { redirect_to @reconocimiento, notice: 'Reconocimiento creado' }
        format.json { render json: @reconocimiento, status: :created, location: @reconocimiento }
      else
        format.html { render action: "new" }
        format.json { render json: @reconocimiento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /reconocimientos/1
  # PUT /reconocimientos/1.json
  def update
    @reconocimiento = Reconocimiento.find(params[:id])

    respond_to do |format|
      if @reconocimiento.update_attributes(params[:reconocimiento])
        format.html { redirect_to @reconocimiento, notice: 'Reconocimiento actualizado' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @reconocimiento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reconocimientos/1
  # DELETE /reconocimientos/1.json
  def destroy
    @reconocimiento = Reconocimiento.find(params[:id])
    @reconocimiento.destroy

    respond_to do |format|
      format.html { redirect_to reconocimientos_url, :notice => "#{@reconocimiento.descripcion} eliminado"  }
      format.json { head :no_content }
    end
  end
end

app/helpers/reconocimientos_helper.rb
module ReconocimientosHelper
end

app/views/reconocimientos/_form.html.erb
<%= form_for(@reconocimiento) do |f| %>

  <%= render :partial => 'shared/errores', :locals => { :modelo => @reconocimiento } %>'

  <div class="control-group">
    <%= f.label :descripcion, :style => "", :class => "control-label", :style => "width:20%" %>
    <div class="controls">
      <%= f.text_field :descripcion, :style => "width:70%"  %>
    </div>
  </div>

  <div class="control-group" style = "text-align:right; width:70%">
    <%= link_to reconocimientos_path, { :class => 'btn-black', :style => "color:white"} do %>
      <i class="icon-white icon-remove"></i> Cancelar 
    <% end %> 
    <%= f.submit 'Guardar', :class => 'btn btn-info', :style => "color:white; margin-left: 5px"  %>
  </div>

<% end %>

app/views/reconocimientos/edit.html.erb
<% titulo 'Editar Reconocimiento' %>

<%= render 'form' %>

<!--
<%= link_to @reconocimiento, { :class => 'btn-black', :style => "color:white"} do %>
  <i class="icon-white icon-search"></i> Ver 
<% end %>
-->

app/views/reconocimientos/index.html.erb
<% titulo 'Reconocimientos' %>

<%= link_to  new_reconocimiento_path, { :class => 'btn-black', :style => "color:white;"} do %>
  <i class="icon-white icon-plus"></i> Crear Reconocimiento 
<% end %>
<br/><br/>

<table class="table table-striped tabla">
  <thead  class="head-blue">
  <tr>
    <th>Descripcion</th>
    <th style="width:30%">Acciones</th>
  </tr>
  </thead>
  <tbody>
<% @reconocimientos.each do |reconocimiento| %>
  <tr>
    <td><p class="desc"><%= reconocimiento.descripcion %></p></td>
    <td><!-- <%= link_to reconocimiento, { :class => 'btn btn-info', :style => "color:white"} do %> 
          <i class="icon-white icon-search"></i> Ver 
        <% end %>-->
        <%= link_to edit_reconocimiento_path(reconocimiento), { :class => 'btn btn-info', :style => "color:white"} do %> 
	  <i class="icon-white icon-edit"></i> Editar 
        <% end %>
        <%= link_to reconocimiento, { :class => 'btn btn-danger', :style => "color:white", method: :delete,  
	  data: { confirm: "¿Estas seguro que quieres eliminar #{reconocimiento.descripcion}?"} } do %> 
          <i class="icon-white icon-remove"></i> Eliminar 
        <% end %>
    </td>

  </tr>
<% end %>
  </tbody>
</table>

<%= render :partial => 'shared/paginacion', :locals => { :coleccion => @reconocimientos } %>

<%= render 'shared/modal' %>

app/views/reconocimientos/new.html.erb
<% titulo 'Nuevo Reconocimiento' %>

<%= render 'form' %>

app/views/reconocimientos/show.html.erb
<% titulo 'Reconocimiento' %>

<div class="grid-row" >
  <div class="labels">Descripcion:</div> 
  <div class="values"><%=  @reconocimiento.descripcion %></div> 
</div>
<br />
<nav>
  <%= link_to reconocimientos_path, { :class => 'btn-black', :style => "color:white;"} do %>
    <i class="icon-white icon-arrow-left"></i> Volver 
  <% end %>
  <%= link_to '/admin', { :class => 'btn-black', :style => "color:white"} do %>
    <i class="icon-white icon-book"></i> Ir a Admin 
  <% end %>
  <%= link_to edit_reconocimiento_path(@reconocimiento), { :class => 'btn-black', :style => "color:white"} do %>
    <i class="icon-white icon-edit"></i> Editar 
  <% end %>
</nav>