config/routes.rb
BcProto3::Application.routes.draw do

  resources :documentos do
    member do 
      get 'indexar'
      get 'datos_documento' #Llena con datos de un documento la ventana modal
    end#do
    collection do 
      get 'dashboard'
    end#do
  end#do

  match 'subir_archivo/:id'          => 'documentos#subir_archivo'
  match 'guardar_archivo'            => 'documentos#guardar_archivo'
  match 'guardar_archivo_conest'     => 'documentos#guardar_archivo_conest'
  match 'subir_teg_hacia_busconest'  => 'documentos#crear_teg_desde_conest'

  resources :personas do
    member do 
      get 'datos_persona' #Llena con datos de una persona en la ventana modal
    end#do
    collection do 
      get 'autocompletar_personas'
    end#do
  end#do

  root :to => "busquedas#busqueda_simple"

  match 'admin' => 'documentos#index'

  devise_for :usuarios, :path_names => { :sign_in => 'iniciar_sesion', :sign_out => 'cerrar_sesion' }

  resources :areas

  resources :estudiantes do
    member do 
      get 'datos_estudiante' #Llena con datos de un estudiante en la ventana modal
    end#do
  end#do

  resources :premios

  resources :mencions

  resources :reconocimientos

  resources :idiomas

  resources :tipo_documentos

  match 'busqueda_simple'     => 'busquedas#busqueda_simple'

  match 'directorio'                   => 'busquedas#directorio'

  match 'directorio/escuelas/:escuela' => 'busquedas#directorio_escuela', :escuela => /biologia|computacion|fisica|geoquimica|matematica|quimica/
  match 'directorio/tipos/:tipo'       => 'busquedas#directorio_tipo'

  match 'directorio/fechas/:fecha'     => 'busquedas#directorio_fecha', :fecha => /(1|2)\d{3}/

  match 'busqueda_avanzada'            => 'busquedas#busqueda_avanzada'

  match 'documentos/descargar/:id'     => 'documentos#descargar'

end

app/models/premio.rb
class Premio < ActiveRecord::Base
  include Utilidades

  attr_accessible :descripcion

  has_many :estudiantes, :dependent => :restrict

  validates :descripcion, :length => { :in => 1..100 }, :uniqueness => true

  before_validation do |premio|
    eliminar_acentos!(premio.descripcion).upcase!
  end
end

app/controllers/premios_controller.rb
class PremiosController < AdminController
  include Utilidades

  # GET /premios
  # GET /premios.json
  def index
    @premios = Premio.order("descripcion").paginate(:page => params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @premios }
    end
  end

  # GET /premios/1
  # GET /premios/1.json
  def show
    @premio = Premio.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @premio }
    end
  end

  # GET /premios/new
  # GET /premios/new.json
  def new
    @premio = Premio.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @premio }
    end
  end

  # GET /premios/1/edit
  def edit
    @premio = Premio.find(params[:id])
  end

  # POST /premios
  # POST /premios.json
  def create
    @premio = Premio.new(params[:premio])

    respond_to do |format|
      if @premio.save
        format.html { redirect_to @premio, notice: 'Premio creado' }
        format.json { render json: @premio, status: :created, location: @premio }
      else
        format.html { render action: "new" }
        format.json { render json: @premio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /premios/1
  # PUT /premios/1.json
  def update
    @premio = Premio.find(params[:id])

    respond_to do |format|
      if @premio.update_attributes(params[:premio])
        format.html { redirect_to @premio, notice: 'Premio actualizado' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @premio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /premios/1
  # DELETE /premios/1.json
  def destroy
    @premio = Premio.find(params[:id])

    eliminar_recurso?(@premio) ? notice_msj = "#{@premio.descripcion} fue eliminado" : alert_msj = "No se puede eliminar #{@premio.descripcion} porque hay al menos un estudiante asociado" 

    respond_to do |format|
      format.html { redirect_to premios_url, alert: alert_msj, notice: notice_msj }
      format.json { head :no_content }
    end
  end
end

app/helpers/premios_helper.rb
module PremiosHelper
end

app/views/premios/_form.html.erb
<%= form_for(@premio, :html => {:class => "form_horizontal"}) do |f| %>

  <%= render :partial => 'shared/errores', :locals => { :modelo => @premio } %>'

  <div class="control-group">
    <%= f.label :descripcion, :style => "", :class => "control-label", :style => "width:20%" %>
    <div class="controls">
      <%= f.text_field :descripcion, :style => "width:70%", :maxlenght => "255"  %>
    </div>
  </div>

  <div class="control-group" style = "text-align:right; width:70%">
    <%= link_to premios_path, { :class => 'btn-black', :style => "color:white"} do %>
      <i class="icon-white icon-remove"></i> Cancelar 
    <% end %> 
    <%= f.submit 'Guardar', :class => 'btn btn-info', :style => "color:white; margin-left: 5px"  %>
  </div>
<% end %>

app/views/premios/edit.html.erb
<% titulo 'Editar Premio' %>

<%= render 'form' %>

<!--
<%= link_to @premio, { :class => 'btn-black', :style => "color:white"} do %>
  <i class="icon-white icon-search"></i> Ver 
<% end %> 
-->

app/views/premios/index.html.erb
<% titulo 'Premios' %>

<%= link_to  new_premio_path, { :class => 'btn-black', :style => "color:white;"} do %>
  <i class="icon-white icon-plus"></i> Crear Premio
<% end %>
<br/><br/>

<table class="table table-striped tabla">
  <thead  class="head-blue">
  <tr>
    <th>Descripcion</th>
    <th style="width:30%">Acciones</th>
  </tr>
  </thead>
  <tbody>
<% @premios.each do |premio| %>
  <tr>
    <td><p class="desc"><%= premio.descripcion %></p></td>
    <td><!--- <%= link_to premio, { :class => 'btn btn-info', :style => "color:white"} do %> 
          <i class="icon-white icon-search"></i> Ver 
        <% end %> -->
        <%= link_to edit_premio_path(premio), { :class => 'btn btn-info', :style => "color:white"} do %> 
	  <i class="icon-white icon-edit"></i> Editar 
        <% end %>
        <%= link_to premio, { :class => 'btn btn-danger', :style => "color:white", method: :delete,  
	  data: { confirm: "¿Estas seguro que quieres eliminar #{premio.descripcion}?"} } do %> 
          <i class="icon-white icon-remove"></i> Eliminar 
        <% end %>
    </td>
  </tr>
<% end %>
  </tbody>
</table>

<%= render :partial => 'shared/paginacion', :locals => { :coleccion => @premios } %>

<%= render 'shared/modal' %>

app/views/premios/new.html.erb
<% titulo 'Crear Premio' %>

<%= render 'form' %>

app/views/premios/show.html.erb
<% titulo 'Premio' %>

<div class="grid-row" >
  <div class="labels">Descripcion:</div> 
  <div class="values"><%=  @premio.descripcion %></div> 
</div>

<br />

<nav>
  <%= link_to premios_path, { :class => 'btn-black', :style => "color:white;margin-right:4px;"} do %>
    <i class="icon-white icon-arrow-left"></i> Volver 
  <% end %>
  <%= link_to '/admin', { :class => 'btn-black', :style => "color:white"} do %>
    <i class="icon-white icon-book"></i> Ir a Admin 
  <% end %>
  <%= link_to edit_premio_path(@premio), { :class => 'btn-black', :style => "color:white"} do %>
    <i class="icon-white icon-edit"></i> Editar 
  <% end %>
</nav>